---
title: "Sp_detection"
author: "Archontis Goumagias"
date: "2022-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=40, fig.height=25, out.width='100%', out.height='100%', fig.align='center')
```

```{r}
## Libraries ##
# Load the appropriate libraries.

# For reading
library(readr)
library(readxl)

# For writing
library(openxlsx)

# For plotting
library(ggplot2)
library(ggpubr)
library(grid)
library(RColorBrewer)

# For processing
library(tidyr)
library(dplyr)
```


```{r}
## Read ##
# Read the data from the .tsv files and store them into a list

# Get the names and store them into a list
# file.list <- list.files(pattern = '*merged.tsv', recursive = TRUE)
# Use the above list to read the corresponding tsv files
# id.list <- lapply(file.list, read_tsv)

data <- read_tsv('data/mOTUs.all.samples.tsv', show_col_types = FALSE)
```

```{r}
# Prepossessing of the data to bring them in the appropriate form for plots
# Also filter them based on the specific cut-off calculated.

old.var.name = '#mOTUs2_clade'
new.var.name = 'Bacterial_species'
  
names(data)[names(data) == old.var.name] <- new.var.name
  
## Species specific detection ##
  
# Detection of the Bifidobacterium longum
detection1 <- data[grep('s__Bifidobacterium longum', data$Bacterial_species), ] %>% mutate(Bacterial_species="Bifidobacterium longum")
  
# Detection of the Bacteroides dorei/vulgatus
detection2 <- data[grep('s__Bacteroides dorei/vulgatus', data$Bacterial_species), ] %>% mutate(Bacterial_species="Bacteroides dorei/vulgatus")
  
# Detection of E. coli
detection3 <- data[grep('s__Escherichia coli', data$Bacterial_species), ] %>% mutate(Bacterial_species="Escherichia coli")


# Make a summary of the data
n <- length(data)
data <- full_join(detection1,detection2,by=colnames(detection1)) %>% full_join(detection3, by=colnames(detection1)) %>% pivot_longer(cols=2:all_of(n), names_to = 'Samples', values_to = 'Counts')
  
## Filter the samples based on the cut_off of reads: N = 1018 (reads per sample) ##
  
# Make another table of the data
cut_off_filtered <- full_join(detection1,detection2,by=colnames(detection1)) %>% full_join(detection3, by=colnames(detection1))
  
# Transpose the data frame
# first remember the names
names <- cut_off_filtered$Bacterial_species
cut_off_filtered <- as.data.frame(t(cut_off_filtered[,-1]))
colnames(cut_off_filtered) <- names
  
# Replace NA values with 0
data[is.na(data)] <- 0
cut_off_filtered[is.na(cut_off_filtered)] <- 0
  
# Filter the samples
cut_off_filtered <- cut_off_filtered %>% filter(`Bifidobacterium longum`>= 1018 | `Escherichia coli` >= 1018 | `Bacteroides dorei/vulgatus` >= 1018)
  
## <--> ##
```


```{r}
# Make a factor variable from the continues counts variable
data$Counts.factor <- cut(data$Counts, seq(1, 18000, 1000))
data <- tidyr::unite(data,"Bac_counts",Bacterial_species, Counts.factor,remove = F)

# Replace the id with ID in the samples column
data$Samples <- gsub("id","ID", data$Samples)

# Also make a new column with the sample ID as factor
data$Sample.ID <- data$Samples
data$Sample.ID <- gsub(".d.*","", data$Sample.ID)
data$Sample.ID <- as.factor(data$Sample.ID)

# Replace the sample names with corresponding day
data$Samples <- gsub("ID.*d","", data$Samples)
data$Samples <- gsub(".s.*","", data$Samples)
data$Samples <- as.numeric(data$Samples)
```


```{r}
# Write the cut-off filtered data
write.xlsx(cut_off_filtered, file = "data/Selected_samples.xlsx", rowNames=TRUE)
```

```{r}
# Get full reports for each id
# I can do this with a for loop

full_report1 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID1")
full_report2 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID2")
full_report3 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID3")
full_report4 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID4")
full_report5 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID5")
full_report6 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID6")
full_report7 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID7")
full_report8 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID8")
full_report9 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID9")
full_report10 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID10")
full_report11 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID11")
full_report12 <- data %>% group_by(Sample.ID) %>% filter(Sample.ID=="ID12")
```

```{r}
## Make plots ##

# Plotting functions
  
pfunc.1 = function(data, x, y, s, col_var, color_vec, t, drop=TRUE) {
    ggplot(data, aes_string(x, y, size = s, col = col_var)) +  geom_point(alpha = 0.8, show.legend = FALSE) +   scale_size_continuous(limits=c(0,18000),breaks=seq(0, 18000, 1000),range=c(0,40)) + scale_colour_manual(values=color_vec, drop=drop) + theme(axis.text.x = element_text(size=20, angle=90, vjust = 0.5), plot.title = element_text(hjust = 0.5, size=30), axis.text.y = element_text(size=20), plot.margin=unit(c(3,0.1,3,0.1), 'cm')) + rremove("xlab") + rremove("ylab") + labs(title = t)
    
  }
  
pfunc.2 = function(data, x, y, s, col_var, color_vec, t, drop=TRUE) {
    ggplot(data, aes_string(x, y, size = s, col = col_var)) +  geom_point(alpha = 0.8, show.legend = FALSE) +   scale_size_continuous(limits=c(0,18000),breaks=seq(0, 18000, 1000),range=c(0,40)) + scale_colour_manual(values=color_vec, drop=drop) + theme(axis.text.x = element_text(size=20, angle=90, vjust = 0.5), plot.title = element_text(hjust = 0.5, size=30), axis.text.y = element_blank(), plot.margin=unit(c(3,0.01,3,0.01), 'cm')) + rremove("xlab") + rremove("ylab") + labs(title = t)
    
  }

## Brewer palette
# Get a vector with Brewer colors Greens
br.colors <- brewer.pal(9,"Greens")
# Reverse the palette
br.colors.r <- br.colors[4:11]
  
## Viridis palette
v <- viridis::inferno(n=57, direction= -1)
  
# Make a fake data frame to build the levels of each species per range of counts.
numbers <- rep(seq(0, 18000, 999), 3)
bac <- c(rep("Escherichia coli", 19), rep("Bifidobacterium longum", 19), rep("Bacteroides dorei/vulgatus", 19))
df <- data.frame(numbers,bac)
df$numbers.factor <- cut(df$numbers, seq(1, 18000, 1000))
df <- tidyr::unite(df,"bac_counts",bac,numbers.factor,remove = F)
col <- setNames(v, levels(factor(df$bac_counts)))

  
# Calling the function for plotting

p1 <- pfunc.1(full_report1,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID1")
p2 <- pfunc.2(full_report2,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID2")
p3 <- pfunc.2(full_report3,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID3")
p4 <- pfunc.2(full_report4,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID4")
p5 <- pfunc.1(full_report5,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID5")
p6 <- pfunc.2(full_report6,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID6")
p7 <- pfunc.2(full_report7,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID7")
p8 <- pfunc.2(full_report8,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID8")
p9 <- pfunc.1(full_report9,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID9")
p10 <- pfunc.2(full_report10,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID10")
p11 <- pfunc.2(full_report11,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID11")
p12 <- pfunc.2(full_report12,"Samples","Bacterial_species","Counts","Bac_counts", col, "ID12")


# Make a list of the plots
plot.list <- list(p1, p2 , p3 , p4, p5, p6, p7, p8, p9, p10, p11, p12)

# Make the multiple plot figure
figure.1 <- ggarrange(plotlist = plot.list, 
                      ncol = 4, nrow = 3, align = "hv", common.legend = FALSE, legend = "bottom", 
                      labels = NULL, 
                      font.label = list(size = 10, color = "black", face = "bold", family = NULL, position = "top"))

figure.1
# Annotate figure
# annotate_figure(figure.1, left = textGrob("Bacterial species", rot = 90, vjust = 1, gp = gpar(cex = 3)), bottom = textGrob("Days since birth", gp = gpar(cex = 1.3)))

```


